[SETTINGS]
# Active environmet: 'production' or 'staging'
environment = staging
prompt_per_vxc = false

[CREDENTIALS]
client_id = 
client_secret = 

[ENDPOINTS_PRODUCTION]
auth_url = https://auth-m2m.megaport.com/oauth2/token
base_url = https://api.megaport.com/v2

[ENDPOINTS_STAGING]
auth_url = https://auth-m2m-staging.megaport.com/oauth2/token
base_url = https://api-staging.megaport.com/v2
