[SETTINGS]
# Active environmet: 'production' or 'staging'
environment = staging
prompt_per_vxc = false

[CREDENTIALS]
client_id = 65vcolfcjtqhg9gczz2s9qn39k
client_secret = q5k4yposylrir77brjow0w8z09wdcac28rg109f4boiv31wcndh6

[ENDPOINTS_PRODUCTION]
auth_url = https://auth-m2m.megaport.com/oauth2/token
base_url = https://api.megaport.com/v2

[ENDPOINTS_STAGING]
auth_url = https://auth-m2m-staging.megaport.com/oauth2/token
base_url = https://api-staging.megaport.com/v2
